#!/bin/bash
a=$DECIMAL
hex_array=("0" "1" "2" "3" "4" "5" "6" "7" "8" "9" "A" "B" "C" "D" "E" "F")
result=""
while [ $a -gt 0 ]; do
	rem=$(($a % 16))
	result="${hex_array[rem]}$result"
	a=$((a / 16))
done
echo "$result"
